import fs from 'fs/promises';
import path from 'path';
import type { ExtractedTool } from './swagger-converter.js';

export interface PythonGeneratorOptions {
  authBasic?: string;
  apiKey?: string;
}

export class PythonGenerator {
  constructor(private outDir: string, private opts: PythonGeneratorOptions = {}) {}

  async generate(tools: ExtractedTool[]): Promise<void> {
    await fs.mkdir(this.outDir, { recursive: true });

    const write = async (name: string, content: string) => {
      await fs.writeFile(path.join(this.outDir, name), content, 'utf-8');
    };

    await write('requirements.txt', this._requirements());
    await write('server.py',        this._renderServer(tools));
    await write('AGENTS.md',        this._renderAgentsMd(tools));
  }

  private _requirements(): string {
    return `mcp>=1.0.0
httpx>=0.27.0
`;
  }

  private _toPyIdent(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
  }

  private _renderServer(tools: ExtractedTool[]): string {
    const services = [...new Set(tools.map(t => t.service))];

    const authBasicLine = this.opts.authBasic
      ? `AUTH_BASIC = os.environ.get("AGENTIFY_AUTH_BASIC", ${JSON.stringify(this.opts.authBasic)})`
      : `AUTH_BASIC = os.environ.get("AGENTIFY_AUTH_BASIC")`;

    const apiKeyLine = this.opts.apiKey
      ? `API_KEY = os.environ.get("AGENTIFY_APIKEY", ${JSON.stringify(this.opts.apiKey)})`
      : `API_KEY = os.environ.get("AGENTIFY_APIKEY")`;

    const toolDefs = tools.map(t => {
      const pyName = this._toPyIdent(t.name);

      // Build typed parameter list
      const params = t.params.map((p, i) => {
        const typ = t.paramTypes[i] ?? 'string';
        const pyType =
          typ === 'number'  ? 'float' :
          typ === 'boolean' ? 'bool'  :
          typ === 'array'   ? 'list'  :
          typ === 'object'  ? 'dict'  :
          'str';
        return `    ${p}: ${pyType} | None = None`;
      }).join(',\n');

      const hasParams = t.params.length > 0;

      // Separate path params from body/query params
      const pathParamPattern = /\{([^}]+)\}/g;
      const pathParams = new Set<string>();
      let m: RegExpExecArray | null;
      const pattern = new RegExp('\\{([^}]+)\\}', 'g');
      let tempPath = t.httpPath;
      while ((m = pattern.exec(tempPath)) !== null) {
        pathParams.add(m[1]);
      }

      // Build path resolution snippet
      const pathResolution = t.params
        .filter(p => pathParams.has(p))
        .map(p => `    path = path.replace("{${p}}", str(${p}) if ${p} is not None else "{${p}}")`)
        .join('\n');

      // Build query/body args dict (non-path params)
      const nonPathParams = t.params.filter(p => !pathParams.has(p));
      const argsDictEntries = nonPathParams.map(p => `"${p}": ${p}`).join(', ');
      const argsDict = nonPathParams.length > 0 ? `{${argsDictEntries}}` : '{}';
      const argsDict2 = `{k: v for k, v in ${argsDict}.items() if v is not None}`;

      const description = t.description.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');

      // Build the HTTP call based on method
      const method = t.httpMethod.toUpperCase();
      let httpCall: string;
      if (method === 'GET' || method === 'HEAD') {
        httpCall = `        resp = await client.${method.toLowerCase()}(url, params=payload, headers=headers, timeout=30)`;
      } else if (method === 'DELETE') {
        httpCall = `        resp = await client.delete(url, headers=headers, timeout=30)`;
      } else {
        // POST, PUT, PATCH — send as JSON body
        httpCall = `        resp = await client.${method.toLowerCase()}(url, json=payload, headers=headers, timeout=30)`;
      }

      return `@mcp.tool()
async def ${pyName}(${hasParams ? '\n' + params + '\n' : ''}) -> dict:
    """${description}"""
    path = "${t.httpPath}"
${pathResolution ? pathResolution + '\n' : ''}    payload = ${argsDict2}
    url = BASE_URL.rstrip("/") + path
    headers: dict[str, str] = {}
    if AUTH_BASIC:
        headers["Authorization"] = f"Basic {AUTH_BASIC}"
    if API_KEY:
        headers["apikey"] = API_KEY
    async with httpx.AsyncClient() as client:
${httpCall}
    try:
        body = resp.json()
    except Exception:
        body = resp.text
    return {"status": resp.status_code, "ok": resp.is_success, "body": body}`;
    }).join('\n\n\n');

    return `#!/usr/bin/env python3
"""
Auto-generated by Agentify — do not edit manually.

Services: ${services.join(', ')}
Tools:    ${tools.length}

Run locally (stdio — for Claude Code / Cursor):
    python server.py

Run as a server (SSE — for Cloud Run / remote deployment):
    PORT=8080 python server.py

Environment variables:
    AGENTIFY_BASE_URL   Required. Base URL of your backend (e.g. http://localhost:8000)
    AGENTIFY_AUTH_BASIC Optional. Basic auth token to inject into every request.
    AGENTIFY_APIKEY     Optional. API key header value to inject into every request.
    PORT                Optional. If set, runs SSE transport on this port instead of stdio.
"""

import os
import sys
import httpx
from mcp.server.fastmcp import FastMCP

BASE_URL = os.environ.get("AGENTIFY_BASE_URL", "")
${authBasicLine}
${apiKeyLine}

if not BASE_URL:
    print("[agentify] WARNING: AGENTIFY_BASE_URL is not set — all tool calls will fail.", file=sys.stderr)

mcp = FastMCP(
    name="agentify-generated",
    instructions="MCP server auto-generated by Agentify. Services: ${services.join(', ')}.",
    port=int(os.environ.get("PORT", 3000)),
)


${toolDefs}


if __name__ == "__main__":
    port = os.environ.get("PORT")
    if port:
        # SSE transport — for Cloud Run, remote deployment, or any HTTP-accessible host
        print(f"[agentify] Starting SSE server on port {port} — ${tools.length} tools across ${services.length} service(s)", file=sys.stderr)
        mcp.run(transport="sse")
    else:
        # stdio transport — for local IDE clients (Claude Code, Cursor, etc.)
        print(f"[agentify] Starting stdio server — ${tools.length} tools across ${services.length} service(s): ${services.join(', ')}", file=sys.stderr)
        mcp.run()
`;
  }

  private _renderAgentsMd(tools: ExtractedTool[]): string {
    const services = [...new Set(tools.map(t => t.service))];

    const byService = services.map(svc => {
      const svcTools = tools.filter(t => t.service === svc);
      const rows = svcTools.map(t => {
        const params = t.params.length > 0 ? t.params.join(', ') : '-';
        return `| \`${t.name}\` | \`${t.httpMethod} ${t.httpPath}\` | ${t.description} | ${params} |`;
      }).join('\n');
      return `### ${svc}\n\n| Tool | Endpoint | Description | Params |\n|---|---|---|---|\n${rows}`;
    }).join('\n\n');

    return `# AGENTS.md
> Auto-generated by Agentify. Re-run \`agentify generate\` to refresh.

## Overview

**${tools.length} tools** across **${services.length} service(s)**: ${services.join(', ')}

Set \`AGENTIFY_BASE_URL\` to your platform base URL before starting the server.

## Tools by Service

${byService}

## Running the Server

### Locally (stdio — Claude Code / Cursor)
\`\`\`bash
AGENTIFY_BASE_URL=http://localhost:8000 python server.py
\`\`\`

### Remote / Cloud Run (SSE)
\`\`\`bash
PORT=8080 AGENTIFY_BASE_URL=https://your-api.com python server.py
\`\`\`

## Connecting to Claude Code (stdio)

Add to \`.mcp.json\` in your project root:

\`\`\`json
{
  "mcpServers": {
    "agentify": {
      "command": "python",
      "args": ["${this.outDir}/server.py"],
      "env": {
        "AGENTIFY_BASE_URL": "http://your-platform:8080"
      }
    }
  }
}
\`\`\`

## Deploying to Cloud Run (SSE)

\`\`\`bash
gcloud run deploy agentify-mcp \\
  --source . \\
  --set-env-vars AGENTIFY_BASE_URL=https://your-api.com \\
  --allow-unauthenticated
\`\`\`
`;
  }
}
