import fs from 'fs/promises';
import path from 'path';
import type { ExtractedTool } from './swagger-converter.js';

export interface PythonGeneratorOptions {
  authBasic?: string;
  apiKey?: string;
}

export class PythonGenerator {
  constructor(private outDir: string, private opts: PythonGeneratorOptions = {}) {}

  async generate(tools: ExtractedTool[]): Promise<void> {
    await fs.mkdir(this.outDir, { recursive: true });

    const write = async (name: string, content: string) => {
      await fs.writeFile(path.join(this.outDir, name), content, 'utf-8');
    };

    await write('requirements.txt', this._requirements());
    await write('handlers.py',      this._renderHandlers(tools));
    await write('server.py',        this._renderServer(tools));
    await write('AGENTS.md',        this._renderAgentsMd(tools));
  }

  private _requirements(): string {
    return `mcp>=1.0.0
requests>=2.31.0
`;
  }

  private _toPyIdent(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
  }

  private _renderHandlers(tools: ExtractedTool[]): string {
    const apiDefs = tools.map(t =>
      `    "${t.name}": {"method": "${t.httpMethod}", "path": "${t.httpPath}"}`
    ).join(',\n');

    const authBasicLine  = this.opts.authBasic
      ? `AUTH_BASIC = os.environ.get("AGENTIFY_AUTH_BASIC", ${JSON.stringify(this.opts.authBasic)})`
      : `AUTH_BASIC = os.environ.get("AGENTIFY_AUTH_BASIC")`;

    const apiKeyLine = this.opts.apiKey
      ? `API_KEY = os.environ.get("AGENTIFY_APIKEY", ${JSON.stringify(this.opts.apiKey)})`
      : `API_KEY = os.environ.get("AGENTIFY_APIKEY")`;

    return `# Auto-generated by Agentify — do not edit manually.
import os
import re
import requests

BASE_URL = os.environ.get("AGENTIFY_BASE_URL", "")
${authBasicLine}
${apiKeyLine}

API_DEFS: dict[str, dict] = {
${apiDefs}
}


def _build_headers() -> dict:
    headers: dict[str, str] = {}
    if AUTH_BASIC:
        headers["Authorization"] = f"Basic {AUTH_BASIC}"
    if API_KEY:
        headers["apikey"] = API_KEY
    return headers


def invoke_tool(name: str, args: dict) -> dict:
    if not BASE_URL:
        raise RuntimeError("AGENTIFY_BASE_URL environment variable is not set.")
    defn = API_DEFS.get(name)
    if not defn:
        raise ValueError(f"No API definition for tool: {name}")

    method = defn["method"]
    raw_path = defn["path"]

    path_param_names = re.findall(r"\\{([^}]+)\\}", raw_path)
    resolved_path = raw_path
    for key in path_param_names:
        val = args.get(key, f"{{{key}}}")
        resolved_path = resolved_path.replace(f"{{{key}}}", str(val))

    body_args = {k: v for k, v in args.items() if k not in path_param_names}

    url = BASE_URL.rstrip("/") + resolved_path
    headers = _build_headers()

    if method == "GET":
        resp = requests.get(url, params=body_args, headers=headers, timeout=30)
    elif method == "POST":
        headers["Content-Type"] = "application/json"
        resp = requests.post(url, json=body_args, headers=headers, timeout=30)
    elif method == "PUT":
        headers["Content-Type"] = "application/json"
        resp = requests.put(url, json=body_args, headers=headers, timeout=30)
    elif method == "PATCH":
        headers["Content-Type"] = "application/json"
        resp = requests.patch(url, json=body_args, headers=headers, timeout=30)
    elif method == "DELETE":
        resp = requests.delete(url, headers=headers, timeout=30)
    else:
        raise ValueError(f"Unsupported HTTP method: {method}")

    try:
        body = resp.json()
    except Exception:
        body = resp.text

    return {"status": resp.status_code, "ok": resp.ok, "body": body}
`;
  }

  private _renderServer(tools: ExtractedTool[]): string {
    const services = [...new Set(tools.map(t => t.service))];

    const toolDefs = tools.map(t => {
      const pyName = this._toPyIdent(t.name);
      const params = t.params.map((p, i) => {
        const typ = t.paramTypes[i] ?? 'string';
        const pyType =
          typ === 'number'  ? 'float' :
          typ === 'boolean' ? 'bool' :
          typ === 'array'   ? 'list' :
          typ === 'object'  ? 'dict' :
          'str';
        return `    ${p}: ${pyType} | None = None`;
      }).join(',\n');

      const argsDict = t.params.length > 0
        ? `{${t.params.map(p => `"${p}": ${p}`).join(', ')}}`
        : '{}';

      const description = t.description.replace(/"/g, '\\"');

      return `@mcp.tool()
def ${pyName}(${params ? '\n' + params + '\n' : ''}) -> dict:
    """${description}"""
    return invoke_tool("${t.name}", ${argsDict})`;
    }).join('\n\n\n');

    return `#!/usr/bin/env python3
# Auto-generated by Agentify — do not edit manually.
# Run: python server.py
# Services: ${services.join(', ')}

from mcp.server.fastmcp import FastMCP
from handlers import invoke_tool

mcp = FastMCP("agentify-generated")


${toolDefs}


if __name__ == "__main__":
    import sys
    print(f"[agentify] MCP server running — ${tools.length} tools across ${services.length} service(s): ${services.join(', ')}", file=sys.stderr)
    mcp.run()
`;
  }

  private _renderAgentsMd(tools: ExtractedTool[]): string {
    const services = [...new Set(tools.map(t => t.service))];

    const byService = services.map(svc => {
      const svcTools = tools.filter(t => t.service === svc);
      const rows = svcTools.map(t => {
        const params = t.params.length > 0 ? t.params.join(', ') : '-';
        return `| \`${t.name}\` | \`${t.httpMethod} ${t.httpPath}\` | ${t.description} | ${params} |`;
      }).join('\n');
      return `### ${svc}\n\n| Tool | Endpoint | Description | Params |\n|---|---|---|---|\n${rows}`;
    }).join('\n\n');

    return `# AGENTS.md
> Auto-generated by Agentify. Re-run \`agentify generate\` to refresh.

## Overview

**${tools.length} tools** across **${services.length} service(s)**: ${services.join(', ')}

Set \`AGENTIFY_BASE_URL\` to your platform base URL before starting the server.

## Tools by Service

${byService}

## Connecting to Claude Code

Add to \`.mcp.json\` in your project root:

\`\`\`json
{
  "mcpServers": {
    "agentify": {
      "command": "python",
      "args": ["${this.outDir}/server.py"],
      "env": {
        "AGENTIFY_BASE_URL": "http://your-platform:8080"
      }
    }
  }
}
\`\`\`
`;
  }
}
